"""VAD conversation server: static front-end + Bengali ASR + local text generation.

Pipeline per turn:
  browser VAD cuts a speech segment  ->  POST /api/sessions/{id}/turns
  -> WAV saved under conversations/<session>/
  -> transcribed with ehzawad/stt_bn_fastconformer_ctc  (asr.py)
  -> optional reply generated by a local Ollama model   (llm.py)

Run with the project venv so NeMo is importable:
    .venv/bin/python server.py
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import time
import uuid
from contextlib import asynccontextmanager
from collections import deque
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, UploadFile, Request
from fastapi.responses import FileResponse, JSONResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from starlette.concurrency import run_in_threadpool

import asr
import llm
import tts
from streaming import router as streaming_router

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(message)s")
log = logging.getLogger("server")

ROOT = Path(__file__).resolve().parent
STATIC = ROOT / "static"
CONVS = ROOT / "conversations"
CONVS.mkdir(exist_ok=True)

SAFE_ID = re.compile(r"^[A-Za-z0-9_-]{1,64}$")
WAV_NAME = re.compile(r"^turn-\d{4}-(file|mic)\.wav$")

# One writer at a time per session: mic turns, file turns and replies can all
# land concurrently, and each one appends to the same turns.json.
_locks: dict[str, asyncio.Lock] = {}
_replies: dict[tuple[str, str], asyncio.Task] = {}
_interrupted: dict[str, deque] = {}


def _lock(session_id: str) -> asyncio.Lock:
    return _locks.setdefault(session_id, asyncio.Lock())


@asynccontextmanager
async def lifespan(app: FastAPI):
    asr.start_loading()          # background; server answers immediately
    yield


app = FastAPI(title="Bengali Voice Bot", lifespan=lifespan)
app.include_router(streaming_router)


# ---------------------------------------------------------------- storage --
def _session_dir(session_id: str, create: bool = False) -> Path:
    if not SAFE_ID.match(session_id):
        raise HTTPException(400, "bad session id")
    d = CONVS / session_id
    if create:
        d.mkdir(parents=True, exist_ok=True)
    elif not d.is_dir():
        raise HTTPException(404, "unknown session")
    return d


def _load(d: Path) -> list[dict]:
    p = d / "turns.json"
    return json.loads(p.read_text()) if p.exists() else []


def _save(d: Path, turns: list[dict]) -> None:
    tmp = d / "turns.json.tmp"
    tmp.write_text(json.dumps(turns, ensure_ascii=False, indent=2))
    os.replace(tmp, d / "turns.json")


# ------------------------------------------------------------------ routes --
@app.get("/")
def index():
    return FileResponse(STATIC / "index.html")


@app.get("/api/health")
def health():
    return {
        "asr": asr.status(),
        "llm": {"available": llm.available(), "model": llm.MODEL, "models": llm.models()},
    }


@app.post("/api/sessions")
def create_session():
    sid = time.strftime("%Y%m%d-%H%M%S") + "-" + uuid.uuid4().hex[:6]
    _session_dir(sid, create=True)
    return {"session_id": sid}


@app.get("/api/sessions")
def list_sessions():
    out = []
    for d in sorted(CONVS.iterdir(), reverse=True):
        if d.is_dir():
            turns = _load(d)
            out.append({
                "session_id": d.name,
                "turns": len(turns),
                "preview": next((t.get("text", "") for t in turns if t.get("text")), ""),
            })
    return out


@app.get("/api/sessions/{session_id}")
def get_session(session_id: str):
    return {"session_id": session_id, "turns": _load(_session_dir(session_id))}


@app.post("/api/sessions/{session_id}/turns")
async def add_turn(
    session_id: str,
    audio: UploadFile = File(...),
    source: str = Form(...),        # "file" | "mic"
    start_ms: float = Form(...),
    end_ms: float = Form(...),
    origin: str = Form(""),
    transcribe: bool = Form(True),
):
    if source not in {"file", "mic"}:
        raise HTTPException(400, "source must be file or mic")
    d = _session_dir(session_id, create=True)
    blob = await audio.read()

    async with _lock(session_id):
        turns = _load(d)
        idx = len(turns) + 1
        fname = f"turn-{idx:04d}-{source}.wav"
        (d / fname).write_bytes(blob)
        placeholder = {"index": idx, "role": "user", "source": source, "file": fname,
                       "text": None, "saved_at": time.time()}
        turns.append(placeholder)
        _save(d, turns)              # reserve the slot before the slow ASR call

    turn = {
        "index": idx,
        "role": "user",
        "source": source,
        "origin": origin,
        "start_ms": round(start_ms, 1),
        "end_ms": round(end_ms, 1),
        "duration_ms": round(end_ms - start_ms, 1),
        "file": fname,
        "text": None,
        "asr_error": None,
        "asr_ms": None,
        "saved_at": time.time(),
    }

    if transcribe:
        t0 = time.perf_counter()
        try:
            turn["text"] = await run_in_threadpool(asr.transcribe, d / fname)
        except Exception as e:
            turn["asr_error"] = str(e)
            log.warning("transcribe failed: %s", e)
        turn["asr_ms"] = round((time.perf_counter() - t0) * 1000)

    async with _lock(session_id):
        turns = _load(d)
        for i, t in enumerate(turns):
            if t["index"] == idx:
                turns[i] = turn
                break
        else:
            turns.append(turn)
        _save(d, turns)
    return turn


class ReplyIn(BaseModel):
    model: str | None = None
    request_id: str = Field(default_factory=lambda: uuid.uuid4().hex, max_length=64)


class SpeechIn(BaseModel):
    text: str = Field(min_length=1, max_length=2000)


@app.post("/api/speech")
async def speech(body: SpeechIn):
    try:
        audio = await tts.synthesize(body.text)
    except (RuntimeError, OSError, TimeoutError) as exc:
        raise HTTPException(503, str(exc))
    return Response(audio, media_type="audio/wav")


class InterruptIn(BaseModel):
    request_id: str = Field(min_length=1, max_length=64)


@app.post("/api/sessions/{session_id}/interrupt")
async def interrupt_reply(session_id: str, body: InterruptIn):
    d = _session_dir(session_id)
    async with _lock(session_id):
        _interrupted.setdefault(session_id, deque(maxlen=128)).append(body.request_id)
        task = _replies.get((session_id, body.request_id))
        if task:
            task.cancel()
        turns = _load(d)
        for turn in turns:
            if turn.get("request_id") == body.request_id:
                turn["interrupted"] = True
        _save(d, turns)
    return {"ok": True}


@app.post("/api/sessions/{session_id}/reply")
async def make_reply(session_id: str, request: Request, body: ReplyIn | None = None):
    """Generate an assistant reply from everything said so far."""
    d = _session_dir(session_id)
    body = body or ReplyIn()
    key = (session_id, body.request_id)
    if body.request_id in _interrupted.get(session_id, ()):
        raise HTTPException(409, "reply interrupted")
    if key in _replies:
        raise HTTPException(409, "reply already in progress")
    turns = _load(d)
    user_index = max((t["index"] for t in turns if t.get("role", "user") == "user"), default=0)
    history = [
        {"role": t.get("role", "user"), "content": t["text"]}
        for t in turns if t.get("text") and not t.get("interrupted")
    ]
    if not history:
        raise HTTPException(400, "nothing transcribed yet")

    t0 = time.perf_counter()
    task = asyncio.create_task(llm.reply_async(history, body.model))
    _replies[key] = task
    try:
        while not task.done():
            await asyncio.wait({task}, timeout=0.1)
            if await request.is_disconnected():
                task.cancel()
                raise HTTPException(499, "client disconnected")
        text = await task
    except asyncio.CancelledError:
        if task.cancelled():
            raise HTTPException(409, "reply interrupted")
        raise
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(503, str(e))
    finally:
        _replies.pop(key, None)
        if not task.done():
            task.cancel()
        await asyncio.gather(task, return_exceptions=True)

    async with _lock(session_id):
        if not d.exists() or body.request_id in _interrupted.get(session_id, ()):
            raise HTTPException(409, "reply interrupted")
        turns = _load(d)
        latest_user = max((t["index"] for t in turns if t.get("role", "user") == "user"), default=0)
        if latest_user != user_index:
            raise HTTPException(409, "new speech superseded this reply")
        turn = {
            "index": len(turns) + 1,
            "role": "assistant",
            "source": "llm",
            "model": (body.model if body and body.model else llm.MODEL),
            "text": text,
            "request_id": body.request_id,
            "gen_ms": round((time.perf_counter() - t0) * 1000),
            "saved_at": time.time(),
        }
        turns.append(turn)
        _save(d, turns)
    return turn


@app.get("/api/sessions/{session_id}/turns/{fname}")
def get_turn_audio(session_id: str, fname: str):
    d = _session_dir(session_id)
    if not WAV_NAME.match(fname):
        raise HTTPException(400, "bad file name")
    p = d / fname
    if not p.exists():
        raise HTTPException(404)
    return FileResponse(p, media_type="audio/wav")


@app.delete("/api/sessions/{session_id}")
async def clear_session(session_id: str):
    d = _session_dir(session_id)
    for (sid, _), task in list(_replies.items()):
        if sid == session_id:
            task.cancel()
    _interrupted.pop(session_id, None)
    for p in d.iterdir():
        p.unlink()
    d.rmdir()
    _locks.pop(session_id, None)
    return JSONResponse({"ok": True})


app.mount("/static", StaticFiles(directory=STATIC), name="static")


def _print_qr(url: str) -> None:
    """Show a scannable code so a phone can open the app without typing."""
    try:
        import qrcode

        q = qrcode.QRCode(border=1)
        q.add_data(url)
        q.make(fit=True)
        m = q.get_matrix()
        print()
        # two rows per line of text, using half-block characters
        for y in range(0, len(m), 2):
            line = ""
            for x in range(len(m[0])):
                top = m[y][x]
                bottom = m[y + 1][x] if y + 1 < len(m) else False
                line += "█" if top and bottom else "▀" if top else "▄" if bottom else " "
            print("  " + line)
        print(f"\n  scan to open {url}")
    except Exception:
        pass


def _lan_addresses() -> list[str]:
    import socket
    import subprocess

    out = subprocess.run(["ip", "-4", "-o", "addr", "show", "scope", "global"],
                         capture_output=True, text=True).stdout
    ips = []
    for line in out.splitlines():
        parts = line.split()
        if len(parts) > 3 and not parts[1].startswith(("docker", "br-", "veth")):
            ips.append(parts[3].split("/")[0])
    return ips or [socket.gethostbyname(socket.gethostname())]


if __name__ == "__main__":
    import uvicorn

    # Bind to every interface by default so other devices on the LAN can use it.
    host = os.environ.get("CTC_HOST", "0.0.0.0")
    port = int(os.environ.get("CTC_PORT", "8443"))
    cert = ROOT / "certs" / "cert.pem"
    key = ROOT / "certs" / "key.pem"
    tls = cert.exists() and key.exists() and os.environ.get("CTC_TLS", "1") != "0"

    scheme = "https" if tls else "http"
    print(f"\n  open on this machine : {scheme}://localhost:{port}")
    lan = _lan_addresses()
    for ip in lan:
        print(f"  share on the network : {scheme}://{ip}:{port}")
    if lan:
        _print_qr(f"{scheme}://{lan[0]}:{port}")
    if tls:
        print("\n  The certificate is self-signed, so each device shows a warning once.")
        print("  Choose Advanced, then Proceed. The microphone needs this HTTPS.\n")
    else:
        print("\n  No certificate found: microphones will only work on localhost.")
        print("  Run ./gen_cert.sh to enable HTTPS for other devices.\n")

    uvicorn.run(
        app, host=host, port=port,
        ssl_certfile=str(cert) if tls else None,
        ssl_keyfile=str(key) if tls else None,
    )
